version: '3.7'

services:
  api:
    container_name: bexs-banco-api
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - $PWD:/app
    image: node:14
    command: 'yarn ts-node -T src/api/server.ts example/input_file.csv'
